version: "3"
services:
  
  nginx:
    image: "nginx"
    ports:
      - 80:80
      - 8081:8081
  
  ruby:
    image: "trakto/ruby-2.5.0:essential"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 1024M
      restart_policy:
        condition: on-failure     
    ports:
      - 8080:8080    
      - 3000:3000
      - 4000:4000
    volumes:
      - "/var/www/ruby/app:/app"
      - "/Users/jorgehsrocha/Documents/Development/traktopro-gh:integrated_folder/ruby_app"
    entrypoint:
      - bash
    tty: true
    stdin_open: true