version: "3"
services:

  nginx:
    build:
     context: ./Applications/Nginx/Development
     dockerfile: Dockerfile 
    ports:
      - 8080:8080
      - 80:80
      - 8081:8081
    entrypoint:
      - bash     
    tty: true
    stdin_open: true      

  ruby:
    build:
     context: ./Applications/Ruby/Development
     dockerfile: Dockerfile 
    ports:
      - 3000:3000  
    volumes:
      - "/Users/jorgehsrocha/Documents/Development:/app"
    entrypoint:
      - bash
    tty: true
    stdin_open: true