version: "3"
services:

  ruby:
    build:
     context: ./Ruby
     dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 1024M
      restart_policy:
        condition: on-failure     
    ports:
      - 3000:3000    
    volumes:
      - "~/Documents/Development:/integrated_folder"
    entrypoint:
      - bash
    tty: true
    stdin_open: true  


  postgres:
    build:
     context: ./Postgres-database
     dockerfile: Dockerfile
    ports:
      - 5432:5432
    entrypoint:
      - bash
    tty: true
    stdin_open: true  

  nodejs:
    build:
     context: ./NodeJS
     dockerfile: Dockerfile     
    ports:
     - 4200:4200
    volumes:
      - "~/Documents/Development:/integrated_folder"
    entrypoint:
      - bash
    tty: true
    stdin_open: true