version: "3"
services:

#  nginx:
#    build:
#     context: ./Applications/Nginx
#     dockerfile: Dockerfile 
#    ports:
#      - 8080:8080
#      - 80:80
#      - 8081:8081
#    entrypoint:
#      - bash     

  ruby:
    build:
     context: ./Applications/Ruby
     dockerfile: Dockerfile 
    ports:
      - 3000:3000  
    volumes:
      - "/Users/jorgehsrocha/Documents/Development/traktopro-gh:/integrated_folder/ruby_app"
    entrypoint:
      - bash
    tty: true
    stdin_open: true
    links:
      - postgres      
    depends_on:
      - postgres

  postgres:
    build:
     context: ./Applications/Postgres-database
     dockerfile: Dockerfile
    ports:
      - 5432:5432
    entrypoint:
      - bash
    tty: true
    stdin_open: true  

  nodejs:
    build:
     context: ./Applications/NodeJS
     dockerfile: Dockerfile     
    ports:
     - 4200:4200
     - 8080:8080
    volumes:
      - "~/Documents/Development:/integrated_folder"
    entrypoint:
      - bash
    tty: true
    stdin_open: true
